apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  containers:
    - name: http-server
      image: httpserver:latest
      imagePullPolicy: Never
      env:
        - name: INSTANCE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_ENV_VAR
          value: blah
        - name: MY_OTHER_ENV_VAR
          value: blah blah blah
