apiVersion: v1
kind: Service
metadata:
  name: http-server-svc
  labels:
    app.kubernetes.io/name: http-server
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
